spring.application.name=library

spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=finalHyfProject;encrypt=false
spring.datasource.username=sa
spring.datasource.password=YourStrongPassword123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#logging
logging.level.org.springframework=INFO

app.jwt.secret=${JWT_SECRET:mySuperLongSecretKeyThatIsAtLeast32Characters!}
app.jwt.expiration=3600000
app.jwt.refresh-expiration=604800000